2024-05-26 17:36:42,912 : INFO : Start of training model...
2024-05-26 17:36:42,912 : INFO : Run_id: 2024-05-26_173642_33958465
2024-05-26 17:36:42,912 : INFO : Start of data load, validation, and transformation for trainset
2024-05-26 17:36:42,913 : INFO : Start of archiving old reject files...
2024-05-26 17:36:42,913 : INFO : End of archiving old reject files...
2024-05-26 17:36:42,913 : INFO : Start of archiving old validation files...
2024-05-26 17:36:42,914 : INFO : End of archiving old validation files...
2024-05-26 17:36:42,919 : INFO : Start of archiving old processed files...
2024-05-26 17:36:42,919 : INFO : End of archiving old processed files...
2024-05-26 17:36:42,919 : INFO : Start of archiving old result files...
2024-05-26 17:36:42,919 : INFO : End of archiving old result files...
2024-05-26 17:36:42,919 : INFO : Start of reading values from schema...
2024-05-26 17:36:42,919 : INFO : End of reading values from schema...
2024-05-26 17:36:42,919 : INFO : Start of validating column length...
2024-05-26 17:36:42,920 : INFO : End of validating column length...
2024-05-26 17:36:42,920 : INFO : Start of validating missing values...
2024-05-26 17:36:42,920 : INFO : End of validating missing values...
2024-05-26 17:36:42,920 : INFO : Start of replacing missing values with NULL...
2024-05-26 17:36:42,920 : INFO : End of replacing missing values with NULL...
2024-05-26 17:36:42,920 : INFO : Start of creating table...
2024-05-26 17:36:42,920 : INFO : Opened training database successfully
2024-05-26 17:36:42,921 : INFO : Tables created successfully
2024-05-26 17:36:42,921 : INFO : Closed training_raw_data_t database successfilly
2024-05-26 17:36:42,921 : INFO : End of creating table...
2024-05-26 17:36:42,921 : INFO : Opened training database successfully
2024-05-26 17:36:42,921 : INFO : Start of inserting data into table...
2024-05-26 17:36:42,921 : INFO : End of inserting data into table...
2024-05-26 17:36:42,921 : INFO : Start of exporting data into CSV...
2024-05-26 17:36:42,921 : INFO : Opened training database successfully
2024-05-26 17:36:42,967 : INFO : End of exporting data to CSV...
2024-05-26 17:36:42,968 : INFO : Start of moving processed files...
2024-05-26 17:36:42,968 : INFO : End of moving processed files...
2024-05-26 17:36:42,968 : INFO : End of data load, validation, and transformation
2024-05-26 17:36:42,968 : INFO : Start of preprocessing training data...
2024-05-26 17:36:42,968 : INFO : Start of reading dataset...
2024-05-26 17:36:42,985 : INFO : End of reading dataset....
2024-05-26 17:36:42,985 : INFO : Start of dropping columns...
2024-05-26 17:36:42,987 : INFO : End of dropping columns...
2024-05-26 17:36:42,987 : INFO : Start of feature encoding...
2024-05-26 17:36:42,989 : INFO : End of feature encoding...
2024-05-26 17:36:42,989 : INFO : Start of dropping columns...
2024-05-26 17:36:42,990 : INFO : End of dropping columns...
2024-05-26 17:36:42,990 : INFO : Start of finding missing values...
2024-05-26 17:36:42,993 : INFO : End of finding missing values...
2024-05-26 17:36:42,993 : INFO : Start of imputing missing values...
2024-05-26 17:36:43,004 : INFO : End of imputing missing values...
2024-05-26 17:36:43,004 : INFO : Start of splitting features and label
2024-05-26 17:36:43,004 : INFO : End of splitting features and label
2024-05-26 17:36:43,004 : INFO : End of preprocessing training data...
2024-05-26 17:36:43,004 : INFO : Start of elbow plotting...
2024-05-26 17:36:43,397 : ERROR : Exception raised while elbow plotting: [Errno 2] No such file or directory: 'C:\\Users\\RETRETA\\Documents\\Python\\ML Upskill\\employee-churn-ML-e2e\\apps\\models\\kmeans_elbow.png'
Traceback (most recent call last):
  File "C:\Users\RETRETA\Documents\Python\ML Upskill\employee-churn-ML-e2e\apps\tuning\cluster.py", line 35, in create_elbow_plot
    plt.savefig('apps/models/kmeans_elbow.png')
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\pyplot.py", line 1223, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\figure.py", line 3388, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backend_bases.py", line 2218, in print_figure
    result = print_method(
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backend_bases.py", line 2068, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backends\backend_agg.py", line 496, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backends\backend_agg.py", line 445, in _print_pil
    mpl.image.imsave(
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\image.py", line 1676, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\PIL\Image.py", line 2456, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\RETRETA\\Documents\\Python\\ML Upskill\\employee-churn-ML-e2e\\apps\\models\\kmeans_elbow.png'
2024-05-26 17:36:43,404 : ERROR : Training model unsuccessful: [Errno 2] No such file or directory: 'C:\\Users\\RETRETA\\Documents\\Python\\ML Upskill\\employee-churn-ML-e2e\\apps\\models\\kmeans_elbow.png'
Traceback (most recent call last):
  File "C:\Users\RETRETA\Documents\Python\ML Upskill\employee-churn-ML-e2e\apps\training\train_model.py", line 42, in train_model
    number_of_clusters = self.cluster.create_elbow_plot(self.X)
  File "C:\Users\RETRETA\Documents\Python\ML Upskill\employee-churn-ML-e2e\apps\tuning\cluster.py", line 45, in create_elbow_plot
    raise e
  File "C:\Users\RETRETA\Documents\Python\ML Upskill\employee-churn-ML-e2e\apps\tuning\cluster.py", line 35, in create_elbow_plot
    plt.savefig('apps/models/kmeans_elbow.png')
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\pyplot.py", line 1223, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\figure.py", line 3388, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backend_bases.py", line 2218, in print_figure
    result = print_method(
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backend_bases.py", line 2068, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backends\backend_agg.py", line 496, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\backends\backend_agg.py", line 445, in _print_pil
    mpl.image.imsave(
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\matplotlib\image.py", line 1676, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Users\RETRETA\anaconda3\envs\employee-churn-e2e-env\lib\site-packages\PIL\Image.py", line 2456, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\RETRETA\\Documents\\Python\\ML Upskill\\employee-churn-ML-e2e\\apps\\models\\kmeans_elbow.png'
